### ISSUE TITLE
知网高级检索不可用

### ISSUE THREAD

**Issue by songyp0505** [Nixiak-nan/easyScholar#12]
请问在知网高级检索时需要设置什么东西吗？我试了一下：
kns.cnki.net/kns8/defaultresult/index 可以正常显示
kns.cnki.net/KNS8/AdvSearch?dbcode=SCDB 和 kns.cnki.net/KNS8/AdvSearch?dbcode=CJFQ 都无法正常显示

**Comment by Nixiak-nan** [comment]
您好，这是因为高级检索时，**改变了url地址**，而插件并没有识别“高级检索”后的url地址，于是插件不工作了。现已经增加了高级检索的url地址，插件可以正常工作。因为这个是一个小问题，所以暂时不在各大商店更新。有需要的话，可以自行下载Github代码，用离线安装的方式安装。
![image](https://user-images.githubusercontent.com/70318059/145698698-5f08a952-52c8-46f1-a550-ba787501e5b0.png)

**Comment by songyp0505** [comment]
好嘞
