### ISSUE TITLE
EI索引以及Google scholar中部分期刊不能正常显示

### ISSUE THREAD

**Issue by TaoRuan-Campus** [Nixiak-nan/easyScholar#13]
请问以后会加入EI核心期刊目录吗？另外有的期刊不能正常显示 比如
https://scholar.google.com/scholar?hl=en&as_sdt=0%2C6&as_ylo=2021&q=Political%2C+economic%2C+social%2C+technological%2C+legal+and+environmental+dimensions+of+electric+vehicle+adoption+in+the+United+States%3A+A+social-media+interaction+analysis&btnG=

![image](https://user-images.githubusercontent.com/55067404/145892279-0e311001-8ced-4734-a9c6-0873891fd3a6.png)

Renewable and Sustainable Energy Reviews期刊是中科院分区1区的期刊但是没有显示

**Comment by TaoRuan-Campus** [comment]
![image](https://user-images.githubusercontent.com/55067404/145892418-abb0c77c-85f2-448a-9593-795aeb470f6f.png)

**Comment by Nixiak-nan** [comment]
您好，感谢您的使用。
- 第一个问题：如果能找到完整数据的话，以后的版本将会支持EI索引。其中查阅资料[1]显示，现在的EI已经不区分核心与非核心数据。所以未来如果能实现该功能，将会显示全部的EI索引。
- 第二个问题：感谢您的反馈，这是因为easyScholar点击引用时，通过获取**GB/T 7714** 中的内容来获得期刊全名字。在绝大部分时候是使用的，但是在该例子中并没有**GB/T 7714**，所以easyScholar不能按预期工作 。未来easyScholar将会改进该功能，以使得显示更为准确。

1. [问12：现在还区分Ei Compendex（核心）数据和Ei Page One（非核心）数据吗？](http://www.eipaperbx.com/mod_static-view-sc_id-5.html)

**Comment by Nixiak-nan** [comment]
第一个问题：将在后续考虑。
第二个问题：已经更新了谷歌学术上的代码逻辑，问题2已经得到解决，将在不久之后更新商店中的扩展。
![tmp1641](https://user-images.githubusercontent.com/70318059/146178149-dad4cc51-2a8e-4791-bb55-66caf4ec61ab.png)

**Comment by yangtzech** [comment]
> 您好，感谢您的使用。
> 
> * 第一个问题：如果能找到完整数据的话，以后的版本将会支持EI索引。其中查阅资料[1]显示，现在的EI已经不区分核心与非核心数据。所以未来如果能实现该功能，将会显示全部的EI索引。
> * 第二个问题：感谢您的反馈，这是因为easyScholar点击引用时，通过获取**GB/T 7714** 中的内容来获得期刊全名字。在绝大部分时候是可以正常工作的，但是在该例子中并没有**GB/T 7714**，所以easyScholar不能按预期工作 。未来easyScholar将会改进该功能，以使得显示更为准确。
> 
> 1. [问12：现在还区分Ei Compendex（核心）数据和Ei Page One（非核心）数据吗？](http://www.eipaperbx.com/mod_static-view-sc_id-5.html)

你好，elsevier官网不定期更行ei检索目录
https://www.elsevier.com/__data/assets/excel_doc/0007/56392/CPXSourceList112021.xlsx
