### ISSUE TITLE
edge浏览器插件无法使用

### ISSUE THREAD

**Issue by 863543073** [Nixiak-nan/easyScholar#14]

**Comment by Nixiak-nan** [comment]
作者在Microsoft Edge版本 96.0.1054.53 (官方内部版本) (64 位)中测试[百度学术](https://xueshu.baidu.com/s?wd=finance&rsv_bp=0&tn=SE_baiduxueshu_c1gjeupa&rsv_spt=3&ie=utf-8&f=8&rsv_sug2=0&sc_f_para=sc_tasktype%3D%7BfirstSimpleSearch%7D)网站，是能够正常显示。
- 请补充更详细的信息方便排查问题
- 若今晚未补充信息，将会关闭此issue
<img width="1065" alt="1639480810(1)" src="https://user-images.githubusercontent.com/70318059/145989009-0b3142a4-11f1-4d46-89a9-c2a34adad9a9.png">
