### ISSUE TITLE
知网中的英文期刊显示问题

### ISSUE THREAD

**Issue by TaoRuan-Campus** [Nixiak-nan/easyScholar#16]
在知网中部分英文期刊不能正常显示，虽然在知网搜索英文文献的可能不多，还是汇报一下。同一篇文章
What does community and social media use look like among early PEV drivers? Exploring how drivers build an online resource through community relations and social media tools

![image](https://user-images.githubusercontent.com/55067404/146449793-ae0a5988-5889-4fd5-be58-193f6bb2d82f.png)

知网就没有显示
![image](https://user-images.githubusercontent.com/55067404/146449855-c06aefea-a709-47d1-80e4-0c20733b8d58.png)

**Comment by Nixiak-nan** [comment]
您好，设计就是这样：知网上不显示英文查询。不过既然有人提了，那就证明还是有需求的，后期有时间我会把该功能加上。感谢您的issue

**Comment by TaoRuan-Campus** [comment]
> 您好，设计就是这样：知网上不显示英文查询。不过既然有人提了，那就证明还是有需求的，后期有时间我会把该功能加上。感谢您的issue

好的！

**Comment by Nixiak-nan** [comment]
> > 您好，设计就是这样：知网上不显示英文查询。不过既然有人提了，那就证明还是有需求的，后期有时间我会把该功能加上。感谢您的issue
> 
> 好的！

您好，知网上已经支持显示英文等级。

![tmp9603](https://user-images.githubusercontent.com/70318059/146544641-ac5e08e5-3802-470e-bc6f-39ea0c3b334c.png)
