### ISSUE TITLE
Some Questions

### ISSUE THREAD

**Issue by liguge** [Nixiak-nan/easyScholar#17]
非常感谢作者的工作！有几个问题。

1，中文的EI期刊在知网不能显示。有计划安排吗？（已在关闭的issue看到了相关回答）

2，《振动、测试与诊断》属于CSCD核心，但却没有显示。
期待您的回复！

**Comment by Nixiak-nan** [comment]
非常感谢您的issue，问题解答如下：
1. 中文的EI期刊是支持的呀。如图所示： [知网搜光学，点击相关度](https://kns.cnki.net/kns8/defaultresult/index)
![tmpD1A](https://user-images.githubusercontent.com/70318059/146536920-1109851c-f6fc-4b5c-af70-25a86c0d8db3.png)

2. 原因已经查明。CSCD数据库中为《振动、测试与诊断》，但是在知网、百度学术上显示为《振动.测试与诊断》，这导致了名称匹配不上。现已经增加了判断条件，已经可以正常显示了，优化后的代码今晚再上传github
![tmp6B8A](https://user-images.githubusercontent.com/70318059/146537700-d25f7ddd-43fa-4236-bcde-07d18f0b0663.png)
![tmp903A](https://user-images.githubusercontent.com/70318059/146537726-0d1b0bee-059e-4777-a892-fc6b0fe12d99.png)

**Comment by liguge** [comment]
> 非常感谢您的issue，问题解答如下：
> 
> 1. 中文的EI期刊是支持的呀。如图所示： [知网搜光学，点击相关度](https://kns.cnki.net/kns8/defaultresult/index)
>    ![tmpD1A](https://user-images.githubusercontent.com/70318059/146536920-1109851c-f6fc-4b5c-af70-25a86c0d8db3.png)
> 2. 原因已经查明。CSCD数据库中为《振动、测试与诊断》，但是在知网、百度学术上显示为《振动.测试与诊断》，这导致了名称匹配不上。此类问题暂时无法解决，只能靠用户反馈后，增加判断条件。现已经增加判断条件，已经可以正常显示了，优化后的代码今晚再上传github
>    ![tmp6B8A](https://user-images.githubusercontent.com/70318059/146537700-d25f7ddd-43fa-4236-bcde-07d18f0b0663.png)
>    ![tmp903A](https://user-images.githubusercontent.com/70318059/146537726-0d1b0bee-059e-4777-a892-fc6b0fe12d99.png)

感谢应该是版本的问题所以EI无法显示，我是chrome浏览器，现在还是4.1版本，感谢您的回复！

**Comment by Nixiak-nan** [comment]
对的，是版本问题。现在Github上的代码已经支持EI检索，但是商店中的还未更新。预计12.25左右更新。在此期间，您可以通过下载Github源代码，以离线安装的方式使用。
