### ISSUE TITLE
建议添加“CCF推荐中文科技期刊目录”

### ISSUE THREAD

**Issue by timilan123** [Nixiak-nan/easyScholar#18]
计算机的同学不仅仅会看国际等级，也会关注国内期刊的等级，建议在知网、谷歌学术上添加“CCF推荐中文科技期刊目录”。
目录地址如下：
https://www.ccf.org.cn/ccftjgjxskwml/

**Comment by Nixiak-nan** [comment]
您好，感谢您的建议。easyScholar现已经支持CCF中文，待下一个版本一起在商店更新。
![tmpD3ED](https://user-images.githubusercontent.com/70318059/146665989-5e1fa6bf-a541-4ddc-b0d6-a023977f5408.png)
![tmp101C](https://user-images.githubusercontent.com/70318059/146665995-8d5286fd-857f-406a-9b80-63bdcc158ae6.png)
![tmp5545](https://user-images.githubusercontent.com/70318059/146665997-4004ec2e-d53e-42b1-a9b7-9b98a9e53493.png)

**Comment by timilan123** [comment]
> 您好，感谢您的建议。easyScholar现已经支持CCF中文，待下一个版本一起在商店更新。 ![tmpD3ED](https://user-images.githubusercontent.com/70318059/146665989-5e1fa6bf-a541-4ddc-b0d6-a023977f5408.png) ![tmp101C](https://user-images.githubusercontent.com/70318059/146665995-8d5286fd-857f-406a-9b80-63bdcc158ae6.png) ![tmp5545](https://user-images.githubusercontent.com/70318059/146665997-4004ec2e-d53e-42b1-a9b7-9b98a9e53493.png)

牛啊 祝越做越好！
