### ISSUE TITLE
聚合显示会议、期刊等级

### ISSUE THREAD

**Issue by yangtzech** [Nixiak-nan/easyScholar#19]
目前是在搜索论文时获取对应期刊的分区，但如果想知道某期刊的分区，要分别去查找sci、ei、pku检索，能否提供一个单独的查询页面，聚合显示期刊的sci、ei、PKU分区和等级。

**Comment by Nixiak-nan** [comment]
不太明白您说的意思。您可以在插件显示列表，同时设置sci、ei、PKU等级，保存后，那么每次搜索论文时，都会显示这几个结果呀？还是您的意思是，专门设计一个页面，负责查询期刊信息，输入期刊名字，就能获得它在各个大学里的等级排名？

**Comment by yangtzech** [comment]
> 不太明白您说的意思。您可以在插件显示列表，同时设置sci、ei、PKU等级，保存后，那么每次搜索论文时，都会显示这几个结果呀？还是您的意思是，专门设计一个页面，负责查询期刊信息，输入期刊名字，就能获得它在各个大学里的等级排名？

后者。

**Comment by Nixiak-nan** [comment]
这种方案我也有考虑过，我想专门设计一个第三方的网站，使用数据库存储，利用elasticsearch进行查询。但是这是后话了，如果有余力的话，我会考虑设计该网站

**Comment by yangtzech** [comment]
> 这种方案我也有考虑过，我想专门设计一个第三方的网站，使用数据库存储，利用elasticsearch进行查询。但是这是后话了，如果有余力的话，我会考虑设计该网站

期待🤝
