### ISSUE TITLE
还是原来的图标好看

### ISSUE THREAD

**Issue by TaoRuan-Campus** [Nixiak-nan/easyScholar#20]
可以使用原先的logo吗 以前的更好看

**Comment by Nixiak-nan** [comment]
很感谢您的建议。但是原来的图标是从网上开源库找的图标，随着后期产品规模的扩大，有可能会有版权纠纷。所以更换一个原创设计图标是最好的选择。换LOGO这件事，最好的时间点是一开始，其次是现在。

你也可以看一下它的原始大图，也许就不会觉得它很丑了。它设计是一个字母e + 地球 + 数学运算符号（代表科研）。

![easyScholar图标](https://user-images.githubusercontent.com/70318059/147019620-c9ee7e6c-e9be-4ebe-927d-0d8cb9c860ab.jpg)
![easyScholar 定稿_画板 1](https://user-images.githubusercontent.com/70318059/147019577-9fa1b468-22ab-491d-9546-c930c6b2cf93.jpg)
![easyScholar 效果图](https://user-images.githubusercontent.com/70318059/147019599-268495c6-1a8e-4dc7-9ca1-fc70a90a1b92.jpg)
![easyScholar](https://user-images.githubusercontent.com/70318059/147019606-8f23a39a-3ed8-4188-a1e5-f241e0eaeca5.jpg)

**Comment by TaoRuan-Campus** [comment]
> 很感谢您的建议。但是原来的图标是从网上开源库找的图标，随着后期产品规模的扩大，有可能会有版权纠纷。所以更换一个原创设计图标是最好的选择。换LOGO这件事，最好的时间点是一开始，其次是现在。
> 
> 你也可以看一下它的原始大图，也许就不会觉得它很丑了。它设计是一个字母e + 地球 + 数学运算符号（代表科研）。
> 
> ![easyScholar图标](https://user-images.githubusercontent.com/70318059/147019620-c9ee7e6c-e9be-4ebe-927d-0d8cb9c860ab.jpg) ![easyScholar 定稿_画板 1](https://user-images.githubusercontent.com/70318059/147019577-9fa1b468-22ab-491d-9546-c930c6b2cf93.jpg) ![easyScholar 效果图](https://user-images.githubusercontent.com/70318059/147019599-268495c6-1a8e-4dc7-9ca1-fc70a90a1b92.jpg) ![easyScholar](https://user-images.githubusercontent.com/70318059/147019606-8f23a39a-3ed8-4188-a1e5-f241e0eaeca5.jpg)

寓意确实还行，但是配色雀食不如以前的好看（略土，个人观点），我自己替换了原来的logo文件夹，不过原来的没有48.jpg

**Comment by Nixiak-nan** [comment]
没事哈，审美千人千面。48.jpg你用新图标也行，因为好像谷歌插件是不涉及到48像素大小的logo，我放上去是以防万一。或者拿旧图标裁剪一下，改个名成48.jpg也行
