### ISSUE TITLE
知网科技核心没有显示

### ISSUE THREAD

**Issue by xiaofan1991** [Nixiak-nan/easyScholar#21]
发现有几个问题：自己是win11，edge浏览器

知网

1. 科技核心论文没有正确标注
2. 如果从高级检索的界面进入，无法正确标注

再提一个建议：能不能增加浙江大学期刊目录，因为现在好多高校和医院都开始用这个论文分区了

谢谢！

**Comment by Nixiak-nan** [comment]
感谢您的issue，问题 答复如下：
1. 不太清楚你说的“科技核心论文”指的哪一个，是《中国科技核心期刊》吗？我看了是可以正常显示的呀。还是你说的是有部分期刊没有正确标注，如果是后者，你可以把期刊名和它的等级发给我哈，我做更正。
2. 首先确保easyScholar版本为4.3（edge商店已经为4.3了，谷歌商店还在审核），如果还是不行。就把URL地址的 kns8，改成KNS8后回车即可。这是因为判断的时候只判断了KNS8，没有对kns8做判断，当然，这两个页面都是一样的（我也没想到知网还有这种大小写不同，但是功能一样的URL链接，可能某位程序员写URL地址的时候，把KNS8写成kns8了），后续的版本也会修复这个小BUG哈。
3. 如果我能获取浙江大学的期刊目录，我后续会增加它的支持。因为我也发现easyScholar目前支持的所有等级期刊，生物、医学、药学这块是个盲区。
