### ISSUE TITLE
是否有可能在Google Scholar Alert的邮件订阅中显示期刊等级

### ISSUE THREAD

**Issue by TaoRuan-Campus** [Nixiak-nan/easyScholar#23]
你好，我想问一下，我在Google Scholar中用关键词订阅了一些Alert，这些邮件中的文章实际上都是Google Scholar的结果，请问有可能在邮件中显示出期刊等级吗？下图是一个示例
![image](https://user-images.githubusercontent.com/55067404/148134384-8b48bb5d-b0f5-4462-9b39-7591b83798a9.png)

**Comment by Nixiak-nan** [comment]
您好，这三天没回，是因为我跑去邮箱订阅去了。从技术的角度来说，有可能在之后会支持，但不一定会支持。因为我觉得科研工作者的邮箱是一个比较隐私的东西，尽量不要在别人的邮箱页面上操作，以免产生不必要的麻烦。

**Comment by TaoRuan-Campus** [comment]
> 您好，这三天没回，是因为我跑去邮箱订阅去了。从技术的角度来说，有可能在之后会支持，但不一定会支持。因为我觉得科研工作者的邮箱是一个比较隐私的东西，尽量不要在别人的邮箱页面上操作，以免产生不必要的麻烦。

明白！也许可以让用户自己设置，默认关闭，需要的自己开启？

**Comment by Nixiak-nan** [comment]
好的，这一个建议会在之后考虑
