### ISSUE TITLE
您好，可否增加翻译快捷键选择开启或者关闭的按钮呢，或者增加其他快捷方式，t经常容易误触，感谢！

### ISSUE THREAD

**Issue by Donjae-Wong** [Nixiak-nan/easyScholar#24]

**Comment by Nixiak-nan** [comment]
该功能已经有了。若您现在使用的插件没有这项功能，请更新到最新版本

**Comment by Dr-Jack-co** [comment]
> 该功能已经有了。若您现在使用的插件没有这项功能，请更新到最新版本

您好，我的版本是4.3，有隐藏翻译内容，能否考虑增加一个能够关闭翻译功能的开关呢？感谢解答！

**Comment by Nixiak-nan** [comment]
> > 该功能已经有了。若您现在使用的插件没有这项功能，请更新到最新版本
> 
> 您好，我的版本是4.3，有隐藏翻译内容 我是win10的系统，浏览器使用的是chrome， 使用英文输入状态在Bing或者Google上搜索的时候，如果选中了前面的字符，再输入字母t也会调用翻译功能，能否考虑增加一个能够关闭翻译功能的开关呢？这样就不容易误触，或者有没有其他方法能够避免这种情况呢？感谢解答！

您好，暂时不考虑设置关闭翻译功能的开关。用户如果防止误触，可以把翻译快捷键设置为一个单词中不常开头的字母，例如V, U、I 之类的。

**Comment by TaoRuan-Campus** [comment]
> > > 该功能已经有了。若您现在使用的插件没有这项功能，请更新到最新版本
> > 
> > 
> > 您好，我的版本是4.3，有隐藏翻译内容 我是win10的系统，浏览器使用的是chrome， 使用英文输入状态在Bing或者Google上搜索的时候，如果选中了前面的字符，再输入字母t也会调用翻译功能，能否考虑增加一个能够关闭翻译功能的开关呢？这样就不容易误触，或者有没有其他方法能够避免这种情况呢？感谢解答！
> 
> 您好，暂时不考虑设置关闭翻译功能的开关。用户如果防止误触，可以把翻译快捷键设置为一个单词中不常开头的字母，例如V, U、I 之类的。

我也遇到了这个问题，换成shift+字母是否更好，或者参照其他软件，ctrl+c+c翻译，感觉误触率就很小了吧

**Comment by fluviusmagnus** [comment]
> > > > 该功能已经有了。若您现在使用的插件没有这项功能，请更新到最新版本
> > > 
> > > 
> > > 您好，我的版本是4.3，有隐藏翻译内容 我是win10的系统，浏览器使用的是chrome， 使用英文输入状态在Bing或者Google上搜索的时候，如果选中了前面的字符，再输入字母t也会调用翻译功能，能否考虑增加一个能够关闭翻译功能的开关呢？这样就不容易误触，或者有没有其他方法能够避免这种情况呢？感谢解答！
> > 
> > 
> > 您好，暂时不考虑设置关闭翻译功能的开关。用户如果防止误触，可以把翻译快捷键设置为一个单词中不常开头的字母，例如V, U、I 之类的。
> 
> 我也遇到了这个问题，换成shift+字母是否更好，或者参照其他软件，ctrl+c+c翻译剪切板内容，感觉误触率就很小了吧

用 shift 其实也不够合理。事实上无论改变大小写还是使用特定字母（况且VUI之类对于德语来说已经极为常用），使用单个字母本身来触发都是不太干净的解决方案。如果暂时无法确定哪种快捷键比较好，最好还是增加一个开关。

**Comment by Nixiak-nan** [comment]
未来的easyScholar，会判断当前选中文本是否是输入框，如果是输入框，就不翻译，否则翻译。而且也会提供给用户关闭翻译的选项。
