### ISSUE TITLE
增加Semantic Scholar支持，以及开放源代码

### ISSUE THREAD

**Issue by liyewen521** [Nixiak-nan/easyScholar#25]
您好，感谢您出色的工作，提供了这么好用的插件，现有如下两个问题。

1. 能否提供对Semantic Scholar的支持，这是一个非常好用的查询论文的网站，而且我看在CCFrank上已经是提供了支持的。
2. 能否开放源代码，那样可以方便大家查找bug，更快的加速软件的迭代。

**Comment by Nixiak-nan** [comment]
您好，感谢您的建议，问题答复如下：
1. Semantic Scholar 是一个非常优秀的论文搜索网站，但是对于该网站的支持有一些难度。没记错的话，CCFRank的支持是使用了CCF期刊里的缩写以匹配期刊名，但是在除了CCF之外的绝大多数数据集里，是没有期刊缩写名的。
2. 暂时不考虑，曾经我也开放了源代码，但是带给我的伤害比收益要大，于是不打算开源了，并且后期也会将该Github project关闭。

**Comment by liyewen521** [comment]
原来如此，谢谢，尊重您的考虑~
