### ISSUE TITLE
微软学术停止服务了 需要移除相关说明和代码吗？

### ISSUE THREAD

**Issue by liguge** [Nixiak-nan/easyScholar#26]

**Comment by Nixiak-nan** [comment]
是的，微软学术已经于2022.1.1日停用，但是插件中目前的展示信息中，仍然保留着微软学术的相关信息。我也有在犹豫是否删除相关说明，因为这样可以防止部分新来的用户产生误会，但是保留相关说明，又可以留下easyScholar曾经支持微软学术的痕迹。我确实在犹豫。
