### ISSUE TITLE
关闭翻译功能

### ISSUE THREAD

**Issue by wjh892521292** [Nixiak-nan/easyScholar#28]
希望添加翻译功能开关的选项，真的很容易误触，而且不能设置ctrl和shift，在批量更改的时候肯定会误触。

**Comment by dvstter** [comment]
真的太需要这个功能了，超级恼人。

**Comment by Nixiak-nan** [comment]
未来的easyScholar，会判断当前选中文本是否是输入框，如果是输入框，就补翻译，否则翻译。而且也会提供给用户关闭翻译的选项。
