### ISSUE TITLE
Firefox上插件无法连接服务器

### ISSUE THREAD

**Issue by Liu-yuansheng** [Nixiak-nan/easyScholar#29]
在Firefox上使用，浏览PubMed时显示无法连接到easyscholar服务器,希望尽早解决

**Comment by Nixiak-nan** [comment]
我这边查看是没有任何问题的哈。您是否有开梯子？有的话，先把梯子关了，待能正常使用后再开梯子。

---
PS. 有收到过其他用户的反馈，使用win11，并且在微软商店安装的火狐浏览器版本，就有您说的这种情况。但是其他版本的火狐（例如自己从官网安装的），就没有问题。
所以我猜测，可能**微软商店安装的火狐浏览器版本**是一个非常新（或特殊？）的版本，导致一些功能在上面无法正常使用。但是由于我目前还是win10，无法复现这个问题，所以我暂时还不能解决这个问题。不清楚您的具体情况如何。
